// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbuwuatoswyjanwpelqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidXd1YXRvc3d5amFud3BlbHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTk4NDIsImV4cCI6MjA3MTQzNTg0Mn0.2Whlw1uE6EywXzT3nHiwSKrEy27y-Q5DyMdCejs-y7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});